#!/usr/bin/env sh
#
# ./passgen
#
# A shell script to generate password.
#
# Usage: passgen [options] decent|strong|hard
#
# Options:
#   -l      Password length.
#   -n      Number of password to generate.
#   -q      Quiet mode to only return the password.
#
# Author: Nicolas Brousse
#

set -e

usage() {
    local binfile=`basename $0`
    echo "Usage: $binfile [options] decent|strong|hard" 1>&2;
    echo ""
    echo "Options:"
    echo "  -l      Password length."
    echo "  -n      Number of password to generate."
    echo "  -q      Quiet mode to only return the password."
    exit 1
}

say() {
    if [ ! "$quiet" = true ]; then
        echo $1
    fi
}

error() {
    echo $1
    echo ""
    usage
}

# Generate password
# See: http://unix.stackexchange.com/questions/45404/why-cant-tr-read-from-dev-urandom-on-osx#answers
genpasswd() {
    LC_CTYPE=C tr -dc ${1} < /dev/urandom | head -c ${2} | xargs
}

# Default values
occurences=1
quiet=false

# Options
while getopts 'l:n:qh' opt; do
    case $opt in
        'l')
            if ! echo $OPTARG | egrep -q '^[0-9]+$'; then
                error '-l must be an integer'
            fi
            length=${OPTARG}
            ;;
        'n')
            if ! echo $OPTARG | egrep -q '^[0-9]+$'; then
                error '-n must be an integer'
            fi
            occurences=${OPTARG}
            ;;
        'q')
            quiet=true
            ;;
        'h'|*)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "$1" ]; then
    usage
fi

# Types of passwords
case $1 in
    'decent')
        [ -z "$length" ] && length=10
        chars='A-Za-z0-9'
        ;;
    'strong')
        [ -z "$length" ] && length=15
        chars='A-Za-z0-9_-+='
        ;;
    'hard')
        [ -z "$length" ] && length=40
        chars='A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)\{\}\[\]\;\~\<\>\-\+='
        ;;
    *)
        echo "'${1}' is not a valid type of password!"
        echo ''
        usage
        ;;
esac

if [ ! "$occurences" -eq "1" ]; then
    say "> Generate $occurences occurences of '$1' password with $length characters"
else
    say "> Generate '$1' password with $length characters"
fi

say ''

for i in $(seq 1 ${occurences})
do
    genpasswd $chars $length
done

say ''
